name: indopustaka
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  validators: 3.0.0
  get: ^4.6.5
  flutter:
    sdk: flutter
  package_info_plus: ^5.0.1
  flutter_pw_validator: ^1.4.2
  sqflite: ^2.0.2
  flutter_easyloading: ^3.0.3
  shared_preferences: ^2.0.13
  epub_view: ^3.0.0
  json_annotation: ^4.5.0
  http: ^1.1.0
  chopper: ^7.0.6
  url_launcher: ^6.1.4
  lottie: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.2.1
  syncfusion_flutter_pdfviewer: ^24.1.45
  flutter_html: ^3.0.0-alpha.5
  flutter_secure_storage: ^9.0.0
  flutter_inappwebview: ^6.0.0
  retrofit: ^4.0.1
  permission_handler: ^11.0.0
  image_gallery_saver: ^2.0.3
  freezed_annotation: ^2.2.0
  google_fonts: ^6.0.0
  path_provider: ^2.0.15
  dio: ^5.2.1+1

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  chopper_generator: ^7.0.4
  retrofit_generator: ^8.0.0
  freezed: ^2.3.2

flutter:
  assets:
    - assets/images/
    - assets/raw/
  fonts:
    - family: Mabella
      fonts:
        - asset: assets/fonts/Mabella.ttf
  uses-material-design: true
